### ISSUE TITLE
Flagger canary somehow created service that Helm didn't like

### ISSUE THREAD

**Issue by cer** [stefanprodan/gitops-linkerd#10]
default          customer-service        47m    False   Helm upgrade failed: rendered manifests contain a resource tha
t already exists. Unable to continue with update: Service "customer-service" in namespace "default" exists and cannot
be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.
io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be s
et to "customer-service"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "d
efault"

**Comment by stefanprodan** [comment]
Yes this is expected, you need to remove the service from the chart. You can do that in the HelmRelease with a kustomize patch delete. Most Flagger users have added a boolean to the values to skip the service, e.g. https://github.com/fluxcd/flagger/blob/main/charts/podinfo/values.yaml#L10

**Comment by cer** [comment]
Sure. I'd meant to file this issue in my application's repo as a reminder to track down why the chart was generating a service. Accidentally created it here instead :-)

**Comment by stefanprodan** [comment]
Ok going to close this as it’s not relevant to this repo. In here Helm is not used for apps
